site_name: Collablite
site_url: https://collablite.kenfau.net
repo_url: "https://github.com/kpfaulkner/collablite"

nav:
    - Home: /index
    - About: /about
    - Getting Started:
        - Installation: /installation
        - Quick Start: /quickstart
