site_name: Collablite
site_url: http://collablite.kenfau.net
repo_url: "https://github.com/kpfaulkner/collablite"

nav:
    - Home: index.md
    - About: /about
    - Getting Started:
        - Installation: /installation
        - Quick Start: /quickstart


theme:
    name: material
    language: en
    font:
        text: Gotham
    palette:
        scheme: slate
        primary: deep purple
        accent: yellow


copyright: Copyright &copy; 2023 Ken Faulkner
extra:
    generator: false
    social:
        - type: Mastodon
          link: @kpfaulkner@hachyderm.io
        - type: github
          link: https://github.com/kpfaulkner
