site_name: Collablite
site_url: https://collablite.kenfau.net
repo_url: "https://github.com/kpfaulkner/collablite"

nav:
    - Home: index.md
    - About: /collablite/about
    - Getting Started:
        - Installation: /collablite/installation
        - Quick Start: /collablite/quickstart


theme:
    name: material
    language: en
    font:
        text: Gotham
    palette:
        scheme: slate
        primary: deep purple
        accent: yellow
