apiVersion: v1
kind: Service
metadata:
  name: collabliteproxy
  annotations:
    external-dns.alpha.kubernetes.io/hostname: proxy.grpc.example.com
  labels:
    k8s-app: collabliteproxyapp
spec:
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - name: http
    port: 50051
    targetPort: http
    protocol: TCP
  - name: envoy-admin
    port: 8081
    targetPort: envoy-admin
    protocol: TCP
  selector:
    k8s-app: collabliteproxyapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabliteproxyapp
  labels:
    k8s-app: collabliteproxyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: collabliteproxyapp
  template:
    metadata:
      labels:
        k8s-app: collabliteproxyapp
    spec:
      containers:
        - name: collabliteenvoy
          image: collabliteenvoy 
          imagePullPolicy: Never
          env:
            - name: LISTEN_PORT
              value: "50051"
            - name: SERVICE_DISCOVERY_ADDRESS
              value: "collabliteservice"
            - name: SERVICE_DISCOVERY_PORT
              value: "50051"
          ports:
            - containerPort: 50051
              name: http
            - name: envoy-admin
              containerPort: 8081
