// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.10
// source: proto/collablite.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CollabLiteClient is the client API for CollabLite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollabLiteClient interface {
	ProcessObjectChanges(ctx context.Context, opts ...grpc.CallOption) (CollabLite_ProcessObjectChangesClient, error)
	ImportObject(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetObject(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	ListObjects(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type collabLiteClient struct {
	cc grpc.ClientConnInterface
}

func NewCollabLiteClient(cc grpc.ClientConnInterface) CollabLiteClient {
	return &collabLiteClient{cc}
}

func (c *collabLiteClient) ProcessObjectChanges(ctx context.Context, opts ...grpc.CallOption) (CollabLite_ProcessObjectChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &CollabLite_ServiceDesc.Streams[0], "/collabproto.CollabLite/ProcessObjectChanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &collabLiteProcessObjectChangesClient{stream}
	return x, nil
}

type CollabLite_ProcessObjectChangesClient interface {
	Send(*ObjectChange) error
	Recv() (*ObjectConfirmation, error)
	grpc.ClientStream
}

type collabLiteProcessObjectChangesClient struct {
	grpc.ClientStream
}

func (x *collabLiteProcessObjectChangesClient) Send(m *ObjectChange) error {
	return x.ClientStream.SendMsg(m)
}

func (x *collabLiteProcessObjectChangesClient) Recv() (*ObjectConfirmation, error) {
	m := new(ObjectConfirmation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *collabLiteClient) ImportObject(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/collabproto.CollabLite/ImportObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collabLiteClient) GetObject(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/collabproto.CollabLite/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collabLiteClient) ListObjects(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/collabproto.CollabLite/ListObjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollabLiteServer is the server API for CollabLite service.
// All implementations must embed UnimplementedCollabLiteServer
// for forward compatibility
type CollabLiteServer interface {
	ProcessObjectChanges(CollabLite_ProcessObjectChangesServer) error
	ImportObject(context.Context, *ImportRequest) (*StatusResponse, error)
	GetObject(context.Context, *GetRequest) (*GetResponse, error)
	ListObjects(context.Context, *ListRequest) (*ListResponse, error)
	mustEmbedUnimplementedCollabLiteServer()
}

// UnimplementedCollabLiteServer must be embedded to have forward compatible implementations.
type UnimplementedCollabLiteServer struct {
}

func (UnimplementedCollabLiteServer) ProcessObjectChanges(CollabLite_ProcessObjectChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessObjectChanges not implemented")
}
func (UnimplementedCollabLiteServer) ImportObject(context.Context, *ImportRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportObject not implemented")
}
func (UnimplementedCollabLiteServer) GetObject(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedCollabLiteServer) ListObjects(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedCollabLiteServer) mustEmbedUnimplementedCollabLiteServer() {}

// UnsafeCollabLiteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollabLiteServer will
// result in compilation errors.
type UnsafeCollabLiteServer interface {
	mustEmbedUnimplementedCollabLiteServer()
}

func RegisterCollabLiteServer(s grpc.ServiceRegistrar, srv CollabLiteServer) {
	s.RegisterService(&CollabLite_ServiceDesc, srv)
}

func _CollabLite_ProcessObjectChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollabLiteServer).ProcessObjectChanges(&collabLiteProcessObjectChangesServer{stream})
}

type CollabLite_ProcessObjectChangesServer interface {
	Send(*ObjectConfirmation) error
	Recv() (*ObjectChange, error)
	grpc.ServerStream
}

type collabLiteProcessObjectChangesServer struct {
	grpc.ServerStream
}

func (x *collabLiteProcessObjectChangesServer) Send(m *ObjectConfirmation) error {
	return x.ServerStream.SendMsg(m)
}

func (x *collabLiteProcessObjectChangesServer) Recv() (*ObjectChange, error) {
	m := new(ObjectChange)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CollabLite_ImportObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollabLiteServer).ImportObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collabproto.CollabLite/ImportObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollabLiteServer).ImportObject(ctx, req.(*ImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollabLite_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollabLiteServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collabproto.CollabLite/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollabLiteServer).GetObject(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollabLite_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollabLiteServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collabproto.CollabLite/ListObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollabLiteServer).ListObjects(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollabLite_ServiceDesc is the grpc.ServiceDesc for CollabLite service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollabLite_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collabproto.CollabLite",
	HandlerType: (*CollabLiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImportObject",
			Handler:    _CollabLite_ImportObject_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _CollabLite_GetObject_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _CollabLite_ListObjects_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessObjectChanges",
			Handler:       _CollabLite_ProcessObjectChanges_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/collablite.proto",
}
